apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  labels:
    app: {{ .Values.app.name }}
    environment: {{ .Values.environment }}
data:
  ENVIRONMENT: {{ .Values.environment }} 