apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: legal-term-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: legal-term-api
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetMemoryUtilization }} 