apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: legal-term-api
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: legal-term-api 