environment: production

app:
  name: legal-term-api
  port: 8000
  replicas: 2
  image:
    repository: ghcr.io/vidip/legal-term-api
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 2 